(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),c=window.BEAN_CONFIG,world=new BeanWorld(c),keys=new Set(),loaded={},touches=new Map();let wind=.35,best=0,last=0,accumulator=0,padJump=false,padPause=false,viewState='',previousHeight=-1;
try{best=Number(localStorage.getItem('bean-best')||0)||0;}catch{}$('best').textContent=best+' m';
const atlas=new Image();atlas.src=BEAN_ASSETS.atlas;atlas.onload=()=>loaded.atlas=atlas;for(const [name,s]of Object.entries(BEAN_ASSETS.sprites)){if(s.src){const im=new Image();im.src=s.src;im.onload=()=>loaded[name]=im;}}
function sprite(name,x,y,w,h,flip=false,alpha=1){const s=BEAN_ASSETS.sprites[name],im=loaded[name]||loaded.atlas;if(!im)return false;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);if(flip)ctx.scale(-1,1);if(loaded[name])ctx.drawImage(im,-w/2,-h/2,w,h);else ctx.drawImage(im,...s.crop,-w/2,-h/2,w,h);ctx.restore();return true;}
function showState(){if(viewState===world.state)return;viewState=world.state;const playing=world.state==='playing';$('overlay').classList.toggle('hidden',playing);document.querySelector('.game-shell').classList.toggle('playing',playing);$('pause').textContent=world.state==='paused'?'▶':'Ⅱ';$('pause').setAttribute('aria-label',world.state==='paused'?'再開':'一時停止');if(playing)return;const states={ready:['JACK & THE BEANSTALK','雲の向こうへ。','葉っぱを登って、<br>空の上の巨人に会いに行こう。','冒険をはじめる'],paused:['TAKE A BREATH','ひとやすみ。','準備ができたら、<br>また空をめざそう。','つづける'],lost:['ONE MORE ADVENTURE','もう一度、空へ。',`今回の高さは ${world.height()} m。<br>風を見ながら、次の葉へ。`,'もう一度あそぶ'],won:['HELLO, GIANT!','雲の上に、到着。','600 m の冒険、達成！<br>巨人に会うことができました。','もう一度あそぶ']};const s=states[world.state];$('overlay-label').textContent=s[0];$('overlay-title').textContent=s[1];$('overlay-copy').innerHTML=s[2];$('start').innerHTML=s[3]+' <span>↗</span>';}
function start(){if(world.state!=='paused')world.reset();world.state='playing';keys.clear();touches.clear();canvas.focus({preventScroll:true});showState();}
function pause(){if(world.state==='playing'){world.state='paused';keys.clear();touches.clear();}else if(world.state==='paused')world.state='playing';showState();}
$('start').onclick=start;$('pause').onclick=pause;$('restart').onclick=()=>{world.reset();start();};$('wind').oninput=e=>{wind=Number(e.target.value)/100;$('wind-value').textContent=e.target.value+'%';};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['ArrowLeft','ArrowRight','ArrowUp',' ','a','d','A','D','Escape'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase());if(!e.repeat&&[' ','ArrowUp'].includes(e.key)){if(world.state==='playing')world.jump();else start();}if(!e.repeat&&e.key==='Escape')pause();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('pointerdown',e=>{if(world.state!=='playing')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{startX:e.clientX,startY:e.clientY,x:e.clientX,t:performance.now(),drag:false,axis:0});});
canvas.addEventListener('pointermove',e=>{const t=touches.get(e.pointerId);if(!t)return;const dx=e.clientX-t.startX,dy=e.clientY-t.startY;if(Math.hypot(dx,dy)>10)t.drag=true;if(t.drag){const delta=e.clientX-t.x;if(Math.abs(delta)>1)t.axis=Math.sign(delta);else if(!t.axis)t.axis=Math.sign(dx);}t.x=e.clientX;});
function release(e){const t=touches.get(e.pointerId);if(!t)return;if(e.type==='pointerup'&&!t.drag&&performance.now()-t.t<300)world.jump();touches.delete(e.pointerId);}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',e=>touches.delete(e.pointerId));canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('blur',()=>{keys.clear();touches.clear();if(world.state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&world.state==='playing')pause();last=0;accumulator=0;});
function input(){let axis=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('a')?1:0);for(const t of touches.values())if(t.drag)axis=t.axis;let pads=[];try{pads=navigator.getGamepads?navigator.getGamepads():[];}catch{}const pad=Array.from(pads).find(Boolean);$('pad-status').textContent=pad?'● ゲームパッド接続中':'ゲームパッド未接続';if(pad){const analog=pad.axes[0]||0;if(Math.abs(analog)>.18)axis=analog;if(pad.buttons[14]?.pressed)axis=-1;if(pad.buttons[15]?.pressed)axis=1;const j=!!pad.buttons[0]?.pressed,p=!!pad.buttons[9]?.pressed;if(j&&!padJump){if(world.state==='playing')world.jump();else start();}if(p&&!padPause)pause();padJump=j;padPause=p;}else{padJump=false;padPause=false;}return axis;}
function draw(){const W=480,H=800,cam=world.camera,p=world.player,sy=y=>H-(y-cam);const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#87c6c1');sky.addColorStop(.55,'#c9e4c8');sky.addColorStop(1,'#f1eac3');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);if(loaded.background)sprite('background',W/2,H/2,W,H);
// Soft atmosphere; image sprites provide the characters and plant artwork.
ctx.fillStyle='#fffbe72e';ctx.beginPath();ctx.arc(370,170,110,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffee3a';for(let i=0;i<8;i++){const yy=((i*173+cam*.18)%1000)-100;ctx.beginPath();ctx.ellipse((i*193)%600-60,yy,125,22,0,0,Math.PI*2);ctx.fill();}
sprite('giant',370,390+Math.min(150,cam*.03),330,330,false,.14+Math.min(.23,cam/22000));
// Repeating vine tiles follow the same central path as the platforms.
for(let y=Math.floor((cam-200)/160)*160;y<cam+H+200;y+=160){const x=240+Math.sin((y-65)/95*1.35)*20;if(!sprite('vine',x,sy(y),110,240)){ctx.fillStyle='#40895a';ctx.fillRect(x-6,sy(y)-90,12,190);}}
for(const l of world.platforms){const yy=sy(l.y);if(yy< -80||yy>H+90)continue;if(!sprite('leaf',l.x,yy+12,l.w*1.28,68,l.x<240)){ctx.fillStyle='#39884b';ctx.fillRect(l.x-l.w/2,yy,l.w,12);}if(l===world.platforms[0]){ctx.fillStyle='#224e40';ctx.font='11px sans-serif';ctx.textAlign='center';ctx.fillText('START',l.x,yy+45);}}
const goalY=sy(c.goalHeight);if(goalY>-200&&goalY<H+300){sprite('giant',240,goalY-65,220,220);ctx.fillStyle='#24513e';ctx.textAlign='center';ctx.font='16px sans-serif';ctx.fillText('雲の上の巨人',240,goalY-170);}
const ps=BEAN_ASSETS.sprites.player;const pw=ps.width||64,ph=ps.height||64;if(!sprite('player',p.x,sy(p.y)-ph*.42,pw,ph,p.face<0)){ctx.fillStyle='#d17749';ctx.fillRect(p.x-12,sy(p.y)-35,24,35);}
if(world.state==='playing'&&wind>0){ctx.strokeStyle='#ffffff65';ctx.lineWidth=1;for(let i=0;i<12;i++){const x=((i*71-world.time*(60+world.gust()*220)*wind)%560+560)%560-40,y=(i*137)%800;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+12+world.gust()*20,y-2);ctx.stroke();}}
const shade=ctx.createLinearGradient(0,H-80,0,H);shade.addColorStop(0,'#16483e00');shade.addColorStop(1,'#16483e70');ctx.fillStyle=shade;ctx.fillRect(0,H-80,W,80);
}
function tick(t){const dt=last?Math.min((t-last)/1000,.1):0;last=t;const axis=input();accumulator+=dt;while(accumulator>=1/120){world.step(1/120,axis,wind);accumulator-=1/120;}const height=world.height();if(height!==previousHeight){$('height').innerHTML=height+' <small>m</small>';$('progress').style.width=Math.min(100,height/6)+'%';previousHeight=height;if(height>best){best=height;$('best').textContent=best+' m';try{localStorage.setItem('bean-best',String(best));}catch{}}}$('wind-state').textContent=wind===0?'風なし':world.gust()*wind>.35?'← 風が吹いている':'← おだやか';showState();draw();requestAnimationFrame(tick);}
window.beanGame={world,start,pause};showState();requestAnimationFrame(tick);
})();

